#!/bin/sh
# Display lighttpd 

if [ "z${1}" = "zconfig" ]; then

        echo "graph_title Lighttpd processes"
        echo "graph_args --base 1000 -l 0"
        echo "graph_category lighttpd"
        echo "graph_vlabel processes"

	echo "busy.label busy_servers"
	echo "busy.draw AREA"
	echo "idle.label idle_servers"
	echo "idle.draw STACK"
	exit 0

fi

if [ "z${url}" = "z" ]; then
	url="http://127.0.0.1/server-status?auto"
fi

OUTPUT=`wget -qO - ${url} | cat`

if [ "z${OUTPUT}" = "z" ]; then

	echo "No valid response from server (${url})"
	exit 1

fi

set -- $OUTPUT

if [ "z${10}" = "z" ] || [ "z${12}" = "z" ]; then

	echo "No valid response from server (${url})"
	exit 1

fi

echo "busy.value ${10}"
echo "idle.value ${12}"
