#!/bin/sh
# Display lighttpd 

if [ "z${1}" = "zconfig" ]; then

        echo "graph_title Lighttpd volume"
        echo "graph_args --base 1000"
        echo "graph_vlabel Kbytes per \${graph_period}"
        echo "graph_category lighttpd"

	echo "volume.label volume"
	echo "volume.type DERIVE"
	echo "volume.max 1000000000"
	echo "volume.min 0"
	exit 0

fi

if [ "z${url}" = "z" ]; then
	url="http://127.0.0.1/server-status?auto"
fi

OUTPUT=`wget -qO - ${url} | cat`

if [ "z${OUTPUT}" = "z" ]; then

	echo "No valid response from server (${url})"
	exit 1

fi

set -- $OUTPUT

if [ "z${6}" = "z" ]; then

	echo "No valid response from server (${url})"
	exit 1

fi

echo "volume.value ${6}"
